### ISSUE TITLE
Crate: `scripting`

### ISSUE THREAD

**Issue by ndouglas** [hornvale/hornvale#121]
### User Story

As an engineer, I want an embedded scripting language so that I can do pretty much anything.

### Description

Just `blackpool`, which mercifully is in an existing project and just needs to be copied over.

### Name

scripting

### Visibility

Private (located in `internal/`)

### Tasks

- [x] Determine the crate's scope and functionality.
- [x] Initialize the crate in the appropriate directory (`crates/` or `internal/`).
- [x] Add a value for the "Crate" field in the project.

### Acceptance Criteria

- [x] The crate has been initialized in the appropriate directory (`crates/` or `internal/`).
- [x] The crate has been added to the workspace `Cargo.toml` file.
- [x] A value for the "Crate" field has been added to the project.
