### ISSUE TITLE
Crate: `parser`

### ISSUE THREAD

**Issue by ndouglas** [hornvale/hornvale#24]
### User Story

As the player, I want a `parser` crate so that my commands are understood.

### Description

Parse player input and transform it into valid commands.

### Name

parser

### Visibility

Public (located in `crates/`)

### Tasks

- [ ] Determine the crate's scope and functionality.
- [ ] Identify public interfaces and types.
- [ ] Initialize the crate in the appropriate directory (`crates/` or `internal/`).
- [ ] Add a value for the "Crate" field in the project.

### Acceptance Criteria

- [ ] The crate has been initialized in the appropriate directory (`crates/` or `internal/`).
- [ ] The crate has been added to the workspace `Cargo.toml` file.
- [ ] A value for the "Crate" field has been added to the project.
