### ISSUE TITLE
Crate: `input`

### ISSUE THREAD

**Issue by ndouglas** [hornvale/hornvale#29]
### User Story

As a player, I want an input reading and processing system so that I can send information to the game.

### Description

Read input, split it into discrete commands on `;`/`then`/`.`, throw it in a queue.

### Name

input

### Visibility

Private (located in `internal/`)

### Tasks

- [x] Determine the crate's scope and functionality.
- [x] Initialize the crate in the appropriate directory (`crates/` or `internal/`).
- [x] Add a value for the "Crate" field in the project.

### Acceptance Criteria

- [x] The crate has been initialized in the appropriate directory (`crates/` or `internal/`).
- [x] The crate has been added to the workspace `Cargo.toml` file.
- [x] A value for the "Crate" field has been added to the project.
