### ISSUE TITLE
Crate: `astronomy`

### ISSUE THREAD

**Issue by ndouglas** [hornvale/hornvale#6]
### User Story

As an engineer, I want an `astronomy` crate so that I can centralize functionality for generating worlds, star maps, determining sunrise and sunset times, etc.

### Description

This crate will cover world generation from an astronomical perspective (e.g. the planet's size, axial tilt, length of day, etc), calculations (sunrise/sunset times, etc), procedural generation of star maps, etc.

### Name

astronomy

### Visibility

Public (located in `crates/`)

### Tasks

- [x] Determine the crate's scope and functionality.
- [ ] Identify public interfaces and types.
- [x] Draft initial documentation and README, including:
  - [x] Introduction and purpose of the crate.
  - [x] Key features and intended use cases.
  - [ ] Outline examples demonstrating key features and use cases.
- [x] Initialize the crate in the appropriate directory (`crates/` or `internal/`).
- [x] Add a value for the "Crate" field in the project.

### Acceptance Criteria

- [x] The README is comprehensive, offering a clear introduction, overview of key features, and example usage.
- [x] The crate has been initialized in the appropriate directory (`crates/` or `internal/`).
- [x] The crate has been added to the workspace `Cargo.toml` file.
- [x] A value for the "Crate" field has been added to the project.
