### ISSUE TITLE
Crate: `test_utilities`

### ISSUE THREAD

**Issue by ndouglas** [hornvale/hornvale#8]
### User Story

As an engineer, I want a `test_utilities ` crate so that I can share test utilities across my various crates.

### Description

An internal crate for test utilities, functions, macros, etc.

### Name

test_utilities

### Visibility

Private (located in `internal/`)

### Tasks

- [x] Determine the crate's scope and functionality.
- [ ] Identify public interfaces and types.
- [x] Draft initial documentation and README, including:
  - [ ] Introduction and purpose of the crate.
  - [ ] Key features and intended use cases.
  - [ ] Outline examples demonstrating key features and use cases.
- [x] Initialize the crate in the appropriate directory (`crates/` or `internal/`).
- [x] Add a value for the "Crate" field in the project.

### Acceptance Criteria

- [x] The README is comprehensive, offering a clear introduction, overview of key features, and example usage.
- [x] The crate has been initialized in the appropriate directory (`crates/` or `internal/`).
- [x] The crate has been added to the workspace `Cargo.toml` file.
- [x] A value for the "Crate" field has been added to the project.
